In [18]:
import numpy as np
import pandas as pd
import os
import time
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import ADASYN
from keras.models import model_from_json
from keras.engine.topology import Layer, InputSpec
from keras import initializers
from keras.models import Model

Load Model

In [57]:
json_file = open('train3_wv_model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights("train3_wv_model.h5")
print("Loaded model from disk")

Loaded model from disk


In [58]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/training_testing/train2_wv.csv",header=None)
n=len(dataset.columns)-1
x_testing = dataset.iloc[:,0:n]
y_testing = dataset.iloc[:,n].values

In [59]:
X = dataset.iloc[:,0:n]
Y = dataset.iloc[:,n].values
X, Y = ADASYN().fit_sample(X, Y)
Y1=[]
for y in Y:
    if(y=='AIMX'):
        Y1.append(0)
    if(y=='BASE'):
        Y1.append(1)
    if(y=='CONT'):
        Y1.append(2)
    if(y=='MISC'):
        Y1.append(3)
    if(y=='OWNX'):
        Y1.append(4)
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y1, test_size = 0.30, random_state = 8)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [60]:
y_testing1=[]
for y in y_testing:
    if(y=='AIMX'):
        y_testing1.append(0)
    if(y=='BASE'):
        y_testing1.append(1)
    if(y=='CONT'):
        y_testing1.append(2)
    if(y=='MISC'):
        y_testing1.append(3)
    if(y=='OWNX'):
        y_testing1.append(4)
x_testing = sc.transform(x_testing)
x_testing1=np.reshape(x_testing,(x_testing.shape[0],x_testing.shape[1],1))

In [61]:
y_pred1 = model.predict(x_testing1)
y_pred=np.argmax(y_pred1,axis=1)

In [62]:
conf_mat = confusion_matrix(y_testing1, y_pred)
print(conf_mat)

[[ 46   0   1   4  16]
 [  0  10   0   6   7]
 [  0   0  26  15   3]
 [  4   1  18 525  42]
 [ 13   5   3  87 192]]


In [63]:
accuracy=accuracy_score(y_pred,y_testing1)
print(accuracy*100,'%')

78.02734375 %
