In [35]:
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import ADASYN

In [178]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/training_testing/train3_dv_lm_iv.csv",header=None)
n=len(dataset.columns)-1

In [179]:
X = dataset.iloc[:,0:n]
Y = dataset.iloc[:,n].values
X, Y = ADASYN().fit_sample(X, Y)

In [180]:
Y1=[]
i=[0,0,0,0,0]
for y in Y:
    if(y=='AIMX'):
        Y1.append(0)
        i[0]=i[0]+1
    if(y=='BASE'):
        Y1.append(1)
        i[1]=i[1]+1
    if(y=='CONT'):
        Y1.append(2)
        i[2]=i[2]+1
    if(y=='MISC'):
        Y1.append(3)
        i[3]=i[3]+1
    if(y=='OWNX'):
        Y1.append(4)
        i[4]=i[4]+1
print(i)

[615, 627, 639, 623, 621]


In [181]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y1, test_size = 0.40, random_state = 8)

In [182]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [183]:
d_train = lgb.Dataset(x_train, label=y_train)
params = {}
params['learning_rate'] = 0.001
params['boosting_type'] = 'gbdt'
params['objective'] = 'multiclass'
params['num_class'] = 5
params['metric'] = 'softmax'
params['sub_feature'] = 0.5
params['num_leaves'] = 30
params['max_depth'] = 30
params['min_data'] = 50

clf = lgb.train(params, d_train, 100)

In [184]:
y_pred=clf.predict(x_test)
y_pred=y_pred.argmax(axis=1)

In [185]:
print(y_pred)

[0 2 1 ... 3 0 1]


In [186]:
print(y_test)

[0, 2, 1, 0, 1, 3, 1, 1, 2, 0, 3, 4, 2, 0, 4, 4, 2, 2, 0, 0, 1, 4, 4, 0, 3, 0, 1, 1, 3, 4, 2, 0, 1, 4, 3, 1, 3, 0, 2, 2, 3, 2, 1, 1, 2, 0, 4, 3, 4, 3, 2, 1, 4, 3, 2, 1, 3, 4, 3, 3, 3, 4, 2, 2, 0, 4, 4, 1, 1, 4, 2, 4, 1, 4, 1, 3, 2, 4, 3, 2, 1, 4, 2, 1, 4, 2, 4, 3, 0, 0, 2, 2, 3, 0, 2, 0, 3, 3, 3, 2, 2, 0, 0, 2, 1, 3, 1, 0, 1, 1, 3, 2, 3, 0, 2, 0, 0, 3, 1, 1, 0, 2, 4, 2, 0, 2, 4, 0, 0, 3, 3, 0, 0, 0, 4, 2, 0, 1, 2, 3, 2, 3, 1, 0, 2, 0, 4, 3, 0, 4, 4, 3, 1, 0, 2, 3, 4, 0, 1, 0, 2, 0, 3, 3, 3, 2, 4, 0, 0, 2, 1, 3, 4, 1, 0, 3, 4, 2, 0, 2, 1, 3, 3, 1, 2, 0, 4, 4, 1, 2, 2, 1, 2, 1, 0, 1, 2, 3, 2, 1, 1, 2, 4, 4, 1, 4, 3, 2, 4, 4, 3, 0, 1, 4, 2, 0, 3, 1, 1, 3, 4, 2, 2, 2, 1, 1, 2, 1, 3, 1, 4, 4, 4, 2, 3, 2, 3, 3, 1, 3, 2, 3, 3, 0, 2, 1, 2, 1, 0, 0, 1, 0, 0, 3, 1, 4, 2, 1, 1, 4, 2, 1, 3, 4, 1, 3, 4, 1, 3, 1, 0, 0, 4, 0, 3, 0, 0, 2, 4, 1, 2, 4, 0, 3, 1, 4, 4, 2, 0, 1, 0, 4, 3, 4, 4, 1, 1, 0, 0, 2, 4, 0, 0, 2, 1, 1, 3, 1, 4, 3, 1, 2, 2, 2, 2, 3, 2, 2, 0, 3, 1, 4, 4, 1, 4, 2, 0, 0, 4, 3, 1, 4, 0, 

In [187]:
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

[[221   3   1   9   8]
 [  0 258   1   0   0]
 [  4   3 236   6   6]
 [ 27  12  31 104  86]
 [ 17  22  14  48 133]]


In [188]:
accuracy=accuracy_score(y_pred,y_test)
print(accuracy*100,'%')

76.16000000000001 %


Testing on unknown dataset

In [189]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/training_testing/train2_dv_lm_iv.csv",header=None)
n=len(dataset.columns)-1
x_testing = dataset.iloc[:,0:n]
y_testing = dataset.iloc[:,n].values

In [190]:
y_testing1=[]
for y in y_testing:
    if(y=='AIMX'):
        y_testing1.append(0)
    if(y=='BASE'):
        y_testing1.append(1)
    if(y=='CONT'):
        y_testing1.append(2)
    if(y=='MISC'):
        y_testing1.append(3)
    if(y=='OWNX'):
        y_testing1.append(4)
x_testing = sc.transform(x_testing)

In [191]:
y_output=clf.predict(x_testing)
y_output=y_output.argmax(axis=1)
print(y_output)

[3 4 0 ... 3 1 4]


In [192]:
print(y_testing1)

[3, 3, 3, 0, 4, 4, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 0, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 4, 4, 4, 4, 4, 1, 4, 4, 4, 0, 4, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 4, 0, 4, 3, 3, 4, 4, 3, 3, 3, 1, 0, 4, 0, 4, 3, 3, 3, 3, 3, 0, 0, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 4, 1, 2, 1, 1, 2, 4, 4, 2, 4, 4, 4, 4, 4, 0, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 0, 0, 4, 4, 4, 0, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 2, 2, 2, 4, 3, 3, 3, 3, 4, 4, 2, 2, 0, 4, 4, 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 3, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 3, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 4, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 4, 1, 4, 4, 4, 4, 4, 4, 4, 3, 3, 

In [193]:
conf_mat = confusion_matrix(y_testing1, y_output)
print(conf_mat)

[[  8   3   8  23  25]
 [  0   1   2   4  16]
 [  2   0   8  19  15]
 [ 41  17  62 231 239]
 [  8  11  34 118 129]]


In [194]:
accuracy=accuracy_score(y_output,y_testing1)
print(accuracy*100,'%')

36.81640625 %
