In [1]:
import numpy as np
import pandas as pd
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import ADASYN

In [2]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/training/train3_dv_lm_iv.csv",header=None)
n=len(dataset.columns)-1

In [3]:
X = dataset.iloc[:,0:n]
Y = dataset.iloc[:,n].values
X, Y = ADASYN().fit_sample(X, Y)

In [4]:
Y1=[]
i=[0,0,0,0,0]
for y in Y:
    if(y=='AIMX'):
        Y1.append(1)
        i[0]=i[0]+1
    if(y=='BASE'):
        Y1.append(2)
        i[1]=i[1]+1
    if(y=='CONT'):
        Y1.append(3)
        i[2]=i[2]+1
    if(y=='MISC'):
        Y1.append(4)
        i[3]=i[3]+1
    if(y=='OWNX'):
        Y1.append(5)
        i[4]=i[4]+1
print(i)

[641, 627, 616, 623, 642]


In [8]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y1, test_size = 0.40, random_state = 8)

In [9]:
clf = RandomForestClassifier(n_estimators = 5, bootstrap=0.001,n_jobs=-1)
trained_model = clf.fit(x_train, y_train)
print(trained_model)

RandomForestClassifier(bootstrap=0.001, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [10]:
y_pred=trained_model.predict(x_test)
print(y_pred)

[2 5 1 ... 1 2 1]


In [11]:
print(y_test)

[2, 5, 1, 1, 1, 1, 5, 1, 2, 4, 2, 2, 1, 1, 3, 4, 5, 2, 4, 1, 2, 1, 1, 2, 2, 1, 4, 5, 1, 5, 5, 1, 5, 3, 1, 5, 3, 4, 3, 3, 1, 1, 5, 4, 4, 3, 2, 4, 3, 1, 2, 5, 1, 1, 2, 2, 5, 5, 4, 5, 4, 4, 1, 2, 5, 1, 2, 2, 4, 5, 4, 4, 5, 5, 1, 3, 3, 4, 4, 2, 5, 5, 1, 5, 5, 2, 4, 5, 2, 5, 3, 1, 3, 2, 5, 5, 3, 1, 3, 1, 3, 3, 4, 5, 5, 5, 1, 4, 1, 5, 3, 5, 4, 5, 1, 2, 5, 2, 3, 4, 3, 3, 4, 3, 2, 1, 5, 4, 1, 1, 5, 2, 5, 2, 4, 4, 4, 5, 4, 3, 1, 4, 1, 4, 4, 3, 3, 3, 1, 5, 2, 4, 1, 3, 3, 1, 3, 3, 5, 3, 3, 5, 5, 1, 4, 1, 2, 4, 3, 4, 5, 3, 2, 3, 1, 5, 2, 4, 2, 3, 1, 1, 2, 2, 5, 1, 1, 4, 4, 4, 2, 3, 4, 1, 1, 1, 4, 5, 1, 2, 1, 1, 3, 1, 5, 5, 5, 1, 2, 5, 3, 1, 4, 4, 3, 3, 2, 2, 3, 3, 1, 1, 5, 4, 2, 3, 2, 5, 3, 4, 3, 4, 3, 2, 5, 2, 3, 2, 2, 3, 4, 3, 2, 2, 1, 3, 1, 2, 4, 2, 3, 3, 2, 2, 3, 4, 3, 4, 3, 1, 4, 3, 5, 1, 4, 2, 1, 2, 4, 1, 2, 5, 5, 2, 1, 2, 3, 2, 4, 3, 5, 4, 1, 5, 3, 5, 2, 2, 2, 1, 4, 2, 5, 4, 2, 2, 4, 3, 1, 1, 1, 2, 3, 4, 4, 1, 3, 3, 1, 1, 3, 1, 2, 2, 2, 4, 1, 5, 5, 5, 3, 2, 2, 5, 1, 4, 1, 2, 1, 2, 4, 3, 4, 

In [12]:
conf_mat = confusion_matrix(y_test,y_pred)
print(conf_mat)

[[235   0   6   9   2]
 [  2 256   0   0   1]
 [  9   1 219  13   7]
 [ 45   8  31  94  81]
 [ 42   6  11  66 116]]


In [13]:
accuracy=accuracy_score(y_pred,y_test)
print(str(accuracy*100)+'%')

73.01587301587301%


Testing on unknown dataset 

In [ ]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/testing/test_jdm_dv_lm_iv.csv",header=None)
x_testing = dataset.iloc[:,:]

In [ ]:
y_output=trained_model.predict(x_output)
print(y_output)