In [2]:
import numpy as np
import pandas as pd
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import ADASYN

In [162]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/training_testing/train3_dv_iv.csv",header=None)
n=len(dataset.columns)-1

In [163]:
X = dataset.iloc[:,0:n]
Y = dataset.iloc[:,n].values
X, Y = ADASYN().fit_sample(X, Y)

In [164]:
Y1=[]
i=[0,0,0,0,0]
for y in Y:
    if(y=='AIMX'):
        Y1.append(1)
        i[0]=i[0]+1
    if(y=='BASE'):
        Y1.append(2)
        i[1]=i[1]+1
    if(y=='CONT'):
        Y1.append(3)
        i[2]=i[2]+1
    if(y=='MISC'):
        Y1.append(4)
        i[3]=i[3]+1
    if(y=='OWNX'):
        Y1.append(5)
        i[4]=i[4]+1
print(i)

[603, 630, 630, 623, 620]


In [165]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y1, test_size = 0.40, random_state = 8)

In [166]:
clf = RandomForestClassifier(n_estimators = 5, bootstrap=0.001,n_jobs=-1)
trained_model = clf.fit(x_train, y_train)
print(trained_model)

RandomForestClassifier(bootstrap=0.001, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [167]:
y_pred=trained_model.predict(x_test)
print(y_pred)

[5 5 3 ... 5 3 4]


In [168]:
print(y_test)

[1, 4, 3, 4, 3, 3, 5, 4, 5, 5, 4, 1, 1, 3, 5, 2, 2, 3, 1, 4, 1, 2, 5, 2, 5, 3, 2, 2, 2, 1, 4, 3, 4, 1, 3, 3, 4, 3, 5, 5, 3, 5, 5, 5, 1, 4, 3, 5, 5, 3, 1, 5, 3, 4, 5, 3, 3, 2, 4, 2, 4, 1, 4, 3, 2, 1, 5, 4, 4, 4, 3, 5, 5, 1, 5, 1, 5, 2, 2, 5, 1, 5, 3, 5, 4, 4, 1, 2, 1, 3, 3, 3, 1, 1, 3, 2, 5, 5, 5, 3, 3, 5, 4, 4, 4, 2, 5, 1, 2, 1, 5, 3, 1, 1, 5, 4, 3, 2, 3, 4, 1, 5, 2, 3, 2, 2, 4, 4, 4, 5, 1, 4, 2, 2, 5, 2, 3, 4, 3, 1, 5, 2, 5, 5, 2, 3, 2, 2, 4, 1, 2, 5, 4, 5, 3, 5, 3, 4, 3, 1, 3, 5, 4, 3, 1, 3, 5, 1, 4, 5, 3, 4, 2, 3, 5, 1, 5, 2, 2, 2, 3, 3, 4, 2, 3, 1, 1, 2, 4, 5, 2, 3, 3, 1, 3, 1, 4, 4, 5, 1, 2, 2, 3, 5, 1, 3, 4, 5, 3, 1, 1, 2, 5, 1, 1, 5, 4, 4, 5, 2, 4, 2, 2, 4, 4, 1, 1, 2, 1, 4, 2, 1, 5, 2, 4, 1, 4, 5, 3, 3, 4, 1, 3, 1, 2, 1, 4, 1, 4, 5, 2, 3, 1, 5, 4, 1, 5, 3, 5, 2, 3, 4, 5, 2, 5, 4, 2, 4, 2, 2, 3, 3, 4, 4, 3, 1, 4, 1, 1, 5, 2, 1, 4, 1, 1, 5, 2, 2, 4, 2, 5, 5, 5, 5, 3, 2, 1, 4, 4, 3, 5, 1, 5, 4, 5, 3, 3, 2, 4, 2, 5, 2, 3, 5, 4, 4, 2, 4, 2, 4, 1, 4, 1, 3, 5, 3, 1, 2, 2, 2, 4, 4, 5, 

In [169]:
conf_mat = confusion_matrix(y_test,y_pred)
print(conf_mat)

[[222   0   4  12   6]
 [  4 252   0   0   0]
 [  7   4 216  21   1]
 [ 50  11  38 100  61]
 [ 30   4  21  69 110]]


In [170]:
accuracy=accuracy_score(y_pred,y_test)
print(str(accuracy*100)+'%')

72.40547063555913%


Testing on unknown dataset 

In [171]:
dataset = pd.read_csv("C:/Users/user/PythonProjects/document-data-extraction/data-extraction/training_testing/train2_dv_iv.csv",header=None)
n=len(dataset.columns)-1
x_testing = dataset.iloc[:,0:n]
y_testing = dataset.iloc[:,n].values

In [172]:
y_testing1=[]
for y in y_testing:
    if(y=='AIMX'):
        y_testing1.append(1)
    if(y=='BASE'):
        y_testing1.append(2)
    if(y=='CONT'):
        y_testing1.append(3)
    if(y=='MISC'):
        y_testing1.append(4)
    if(y=='OWNX'):
        y_testing1.append(5)

In [173]:
y_output=trained_model.predict(x_testing)
print(y_output)

[1 2 5 ... 4 4 1]


In [174]:
print(y_testing1)

[4, 4, 4, 1, 5, 5, 5, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 1, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 5, 5, 5, 5, 5, 2, 5, 5, 5, 1, 5, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 5, 1, 5, 4, 4, 5, 5, 4, 4, 4, 2, 1, 5, 1, 5, 4, 4, 4, 4, 4, 1, 1, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 5, 2, 3, 2, 2, 3, 5, 5, 3, 5, 5, 5, 5, 5, 1, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 1, 1, 5, 5, 5, 1, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 3, 3, 3, 5, 4, 4, 4, 4, 5, 5, 3, 3, 1, 5, 5, 5, 5, 5, 4, 4, 4, 4, 5, 5, 5, 4, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 4, 4, 4, 4, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 5, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 5, 2, 5, 5, 5, 5, 5, 5, 5, 4, 4, 

In [175]:
conf_mat = confusion_matrix(y_testing1, y_output)
print(conf_mat)

[[ 13   2  11  30  11]
 [  4   0   5   9   5]
 [  4   4   6  19  11]
 [107  42  86 252 103]
 [ 63  13  40 112  72]]


In [176]:
accuracy=accuracy_score(y_output,y_testing1)
print(accuracy*100,'%')

33.49609375 %
